import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

Font.register({
  family: "Helvetica",
  fonts: [
    { src: "Helvetica" },
    { src: "Helvetica-Bold", fontWeight: "bold" },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1f2937",
    lineHeight: 1.4,
  },
  coverPage: {
    padding: 40,
    fontFamily: "Helvetica",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 200,
    color: "#1a1a1a",
  },
  coverSubtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "#6b7280",
    marginTop: 12,
  },
  coverMeta: {
    fontSize: 12,
    textAlign: "center",
    color: "#9ca3af",
    marginTop: 8,
  },
  coverDate: {
    fontSize: 10,
    textAlign: "center",
    color: "#9ca3af",
    marginTop: 24,
  },
  moduleTitle: {
    fontSize: 14,
    fontWeight: "bold",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
    paddingBottom: 4,
    marginBottom: 12,
    marginTop: 4,
    color: "#1a1a1a",
  },
  questionBlock: {
    marginBottom: 16,
  },
  qtypeBadge: {
    fontSize: 8,
    color: "#6b7280",
    marginBottom: 2,
  },
  question: {
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#1a1a1a",
  },
  answer: {
    fontSize: 10,
    lineHeight: 1.5,
    color: "#374151",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
  },
});

const QTYPE_LABELS: Record<string, string> = {
  B: "Behavioral",
  T: "Technical",
  P: "Problem",
  C: "Culture",
  S: "Scenario",
  L: "Leadership",
};

interface BoardForPDF {
  company_name: string;
  role: string;
  round_type: string;
  total_questions: number;
  modules: Array<{
    title: string;
    cards: Array<{ num: number; q: string; a: string; qtype: string }>;
  }>;
}

export function BoardPDFDocument({ board }: { board: BoardForPDF }) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <Document>
      {/* Cover Page */}
      <Page size="LETTER" style={styles.coverPage}>
        <Text style={styles.coverTitle}>{board.company_name}</Text>
        <Text style={styles.coverSubtitle}>
          {board.role} — {board.round_type} Round
        </Text>
        <Text style={styles.coverMeta}>
          {board.total_questions} questions · {board.modules.length} modules
        </Text>
        <Text style={styles.coverDate}>{date}</Text>
        <Text style={styles.footer}>Generated by JobPrep AI</Text>
      </Page>

      {/* Content Pages — one per module */}
      {board.modules.map((mod, mi) => (
        <Page key={mi} size="LETTER" style={styles.page} wrap>
          <Text style={styles.moduleTitle}>{mod.title}</Text>
          {mod.cards.map((card) => (
            <View key={card.num} style={styles.questionBlock} wrap={false}>
              <Text style={styles.qtypeBadge}>
                [{QTYPE_LABELS[card.qtype] || card.qtype}]
              </Text>
              <Text style={styles.question}>
                Q{card.num}: {card.q}
              </Text>
              {card.a && <Text style={styles.answer}>{card.a}</Text>}
            </View>
          ))}
          <Text style={styles.footer} fixed>
            Generated by JobPrep AI
          </Text>
        </Page>
      ))}
    </Document>
  );
}
